### ISSUE TITLE
Not seeing Authorization headers

### ISSUE THREAD

**Issue by emilva** [gmlewis/go-httpdebug#1] opened 2022-03-11 09:51 UTC
Hi @gmlewis 👋 

I am using your library with `oauth2.StaticTokenSource`, and when the requests are logged I see no `REDACTED` header fields in the curl output. 

Below you can see my whole http client configuration, excuse the mess :D 

```
	transport := &oauth2.Transport{
		Source: oauth2.StaticTokenSource(
			&oauth2.Token{
				AccessToken: token,
			},
		),
		Base: &transportHeaders{
			modifiedSince: time.Now().AddDate(0,0,-1).Format("Thu, 22 Dec 2017 07:51:19 UTC"),
		},
	}

	ct := dbg.New(dbg.WithTransport(transport))

	transporta := &httpcache.Transport{
		Transport:           ct,
		Cache:               diskcache.New("cache"),
		MarkCachedResponses: true,
	}

	hcli := &http.Client{Transport: transporta}

``` 

The output is typically:
```
2022/03/11 10:43:53 curl -X GET \
  https://github.enterprise/api/v3/orgs/finn/teams/billing/repos?per_page=100 \
  -H 'Accept: application/vnd.github.mercy-preview+json' \
  -H 'If-None-Match: W/"3a3ae4bfaa7c0fadae157f58146911ccf7822215d16afc34ae7bef87e11f8dda"' \
  -H 'User-Agent: go-github'
```

Cheers,

emil

**Comment by gmlewis** [comment] 2022-03-11 12:38
Hi @emilva - thanks for the report.  I'm unable to reproduce the problem you are seeing with that snippet.
Here's what I get:

```bash
$ go run main.go
# command-line-arguments
./main.go:25:9: cannot use &transportHeaders{…} (value of type *transportHeaders) as type http.RoundTripper in struct literal:
	*transportHeaders does not implement http.RoundTripper (missing RoundTrip method)
./main.go:26:4: unknown field 'modifiedSince' in struct literal of type transportHeaders
./main.go:32:17: undefined: httpcache
./main.go:34:24: undefined: diskcache
./main.go:38:2: hcli declared but not used
```

Can you please send me a complete program (without the `token` obviously) that can reproduce the issue you are seeing?

**Comment by emilva** [comment] 2022-03-11 12:54
of course, I just sent parts of the configuration.

I managed to reproduce it with this simple go file:
```go
package main

import (
	"context"
	dbg "github.com/gmlewis/go-httpdebug/httpdebug"
	"github.com/google/go-github/v43/github"
	"golang.org/x/oauth2"
)

func main() {

	ctx := context.Background()
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: "xyz"},
	)
	tc := oauth2.NewClient(ctx, ts)

	ct := dbg.New(dbg.WithTransport(tc.Transport))
	client := github.NewClient(ct.Client())
	opts := github.ListOptions{Page: 100}
	client.Teams.ListTeams(ctx, "finn", &opts)

}
```

Output from `go run main.go`:

```
2022/03/11 13:51:28 curl -X GET \
  https://api.github.com/orgs/finn/teams?page=100 \
  -H 'Accept: application/vnd.github.v3+json' \
  -H 'User-Agent: go-github'
```

**Comment by gmlewis** [comment] 2022-03-11 15:02
Thank you, @emilva !   Whups!!!  My bad.  I'll update the repo on how to use it.  Please try this instead:

```go
func main() {

	ctx := context.Background()
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: "xyz"},
	)
	// tc := oauth2.NewClient(ctx, ts)
	tc := &oauth2.Transport{Source: ts, Base: dbg.New()}

	client := github.NewClient(&http.Client{Transport: tc})

	// ct := dbg.New(dbg.WithTransport(tc.Transport))
	// client := github.NewClient(ct.Client())
	opts := github.ListOptions{Page: 100}
	client.Teams.ListTeams(ctx, "finn", &opts)

}
```

With this version, I now get this output:

```bash
$ go run main.go
2022/03/11 10:00:58 curl -X GET \
  https://api.github.com/orgs/finn/teams?page=100 \
  -H 'Accept: application/vnd.github.v3+json' \
  -H 'Authorization: <REDACTED>' \
  -H 'User-Agent: go-github'
```

**Comment by gmlewis** [comment] 2022-03-11 15:13
Fixed documentation in: https://github.com/gmlewis/go-httpdebug/releases/tag/v0.0.5
Closing issue as resolved.

**Closed as completed by gmlewis** 2022-03-11 15:13 UTC

**Comment by emilva** [comment] 2022-03-12 16:14
great, thank you @gmlewis!
